# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-21 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180321_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
