# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-21 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180321_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='r_image',
            new_name='photo_id',
        ),
        migrations.RenameField(
            model_name='views',
            old_name='v_image',
            new_name='photo_id',
        ),
    ]
