# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 10:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180321_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='th',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=b'photos/profile/thumbs', verbose_name=b'Thumb'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photos',
            name='upload_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL),
        ),
    ]
