# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20180323_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='dd',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='img',
            name='th',
            field=models.ImageField(blank=True, null=True, upload_to=b'photos/profile/thumbs', verbose_name=b'Thumb'),
        ),
    ]
