# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180329_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_pic',
            old_name='user',
            new_name='owner',
        ),
    ]
