# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-11 08:47
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0015_auto_20180329_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_time', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('comment', models.TextField()),
                ('comment_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replycomment', to='app.Comments')),
            ],
        ),
        migrations.AddField(
            model_name='photos',
            name='caption',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile_pic',
            name='profile_original',
            field=models.ImageField(blank=True, null=True, upload_to=b'photos/profile/original'),
        ),
        migrations.AlterField(
            model_name='profile_pic',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=b'photos/profile/photo'),
        ),
        migrations.AlterField(
            model_name='profile_pic',
            name='profile_thumbs',
            field=models.ImageField(blank=True, null=True, upload_to=b'photos/profile/thumbs'),
        ),
    ]
